### PR TITLE
Updated code with `ng lint`, prettier, and added prettier pre-commit hook

### PR DESCRIPTION
**Pull request by jadurani**
# Overview

- Ran `ng lint`, revised as requested by linter
- Ran prettier (`prettier "src/app/** --write"`) -- prettier also installed globally

# Trello ticket

https://trello.com/c/BmZ6aif8

### CODE REVIEW

**Comment by rhod8215** [comment]
android phone model: Vivoy55s app testing
-can't log in using facebook
-can't log in using gmail
-'taking photo' feature on request-disposal : household-app experiencing frequent crashes

**Comment by rhod8215** [comment]
using laptop browser:
-signing in using google works fine
-signing in using facebook: error- app is still in dev mode
-can't cancel request

**Comment by jadurani** [comment]
> android phone model: Vivoy55s app testing
> -can't log in using facebook
> -can't log in using gmail
> -'taking photo' feature on request-disposal : household-app experiencing frequent crashes
> -can't cancel request

Can you include the screenshot or screencast when you encounter these issues? 
Did you use prod build?

**Comment by rhod8215** [comment]
"ionic cordova build android" yan po ung ginamit ko po.

**Comment by rhod8215** [comment]
https://drive.google.com/open?id=11wleM9VAcrwFsc30pamHnRsiIwWJM8mL
cancel req parin po. 
undefined po ata nirereturn ng household.id

**Comment by jadurani** [comment]
> https://drive.google.com/open?id=11wleM9VAcrwFsc30pamHnRsiIwWJM8mL
> cancel req parin po.
> undefined po ata nirereturn ng household.id

confirmed issue. Will address here:
https://trello.com/c/zlEU2Q6O

**Pull request merged**
